import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/navabr/TopNav";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Match",
  description: "Generated by Sarraf",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <main className="container mx-auto p-10">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
